export const packages = [
  {
    id: "starter",
    name: "Starter",
    price: "₹14,999",
    note: "one-time from",
    popular: false,
    bestFor: "Shops, small clinics, and simple business sites that need a clean launch.",
    cta: "Get started",
    includes: [
      "Logo design (basic brand kit)",
      "5–7 page custom website",
      "Domain (1st year) + DNS setup",
      "Hosting setup + SSL",
      "WhatsApp & click-to-call CTA",
      "1 month care included",
    ],
  },
  {
    id: "growth",
    name: "Growth",
    price: "₹29,999",
    note: "one-time from",
    popular: true,
    bestFor: "Restaurants, hotels, and hospitals — our most requested package.",
    cta: "Book a call",
    includes: [
      "Everything in Starter",
      "Custom UI with stronger visuals",
      "Enquiry / booking WhatsApp flows",
      "Local SEO basics + Google Business guidance",
      "Gallery / menu / services sections",
      "3 months care included",
    ],
  },
  {
    id: "business",
    name: "Business",
    price: "₹49,999",
    note: "one-time from",
    popular: false,
    bestFor: "Growing brands that need more pages, flows, and polish.",
    cta: "Start now",
    includes: [
      "Everything in Growth",
      "Ecommerce module or advanced forms",
      "Optional AI chatbot setup",
      "Performance & analytics setup",
      "Priority support during build",
      "Ongoing maintenance plan options",
    ],
  },
  {
    id: "custom",
    name: "Custom",
    price: "₹79,999+",
    note: "individually quoted",
    popular: false,
    bestFor: "Shops, portals, multilingual, or anything beyond a standard package.",
    cta: "Request a quote",
    includes: [
      "6+ pages or custom IA",
      "Shop / portal modules",
      "Payments & third-party integrations",
      "AI / automation options",
      "Multilingual (Kannada / English / Telugu)",
      "Scoped after a short discovery call",
    ],
  },
] as const;

export const addOns = [
  { name: "AI Chatbot setup", price: "from ₹7,999" },
  { name: "Extra pages", price: "from ₹1,499 / page" },
  { name: "Ecommerce module", price: "from ₹19,999" },
  { name: "Multilingual (Kannada / English / Telugu)", price: "Custom quote" },
  { name: "Extra maintenance months", price: "from ₹1,999 / month" },
  { name: "Content writing support", price: "Custom quote" },
] as const;
